# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  tfsec:
    name: tfsec
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Terraform security scan wrong
        uses: triat/terraform-security-scan@18-allow-multiple-directories
        with:
          tfsec_actions_working_dir: wrong wrong2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Terraform security scan
        uses: triat/terraform-security-scan@18-allow-multiple-directories
        with:
          tfsec_actions_working_dir: correct correct2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
